In [19]:
import pandas as pd
from sklearn.utils import shuffle
from sklearn import preprocessing

In [20]:
def numeric_columns(df):
    numeric_cols = []
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            numeric_cols.append(col)
    return numeric_cols
# Load dataset
df = pd.read_csv("no_loc_updated.csv")

# Use function to extract numeric columns
numeric_cols = numeric_columns(df)
# print(df_num.shape)
# print(df_num.columns)
# print(df_num['MHW_count'].value_counts())

# Create a copy of the DataFrame
df_numeric = df[numeric_cols].copy()

# Now you can safely modify df_numeric
df_numeric['mhw_category'] = df['mhw_category']

replace_category = {
    'none': 0,
    'Moderate': 1,
    'Strong': 2,
    'Severe': 3
}

df_numeric['mhw_category'] = df['mhw_category'].replace(replace_category)

print(df_numeric['mhw_category'].value_counts())

# Shuffle the DataFrame
shuffled_df_numeric = shuffle(df_numeric, random_state=42)

# Separate features (X) and labels (y) after shuffling
X = shuffled_df_numeric.drop(['mhw_category', 'mhw_count'], axis=1)
y = shuffled_df_numeric['mhw_category']
X.shape, y.shape

mhw_category
0    3245
1     605
2     185
3      31
Name: count, dtype: int64

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_15708\996968386.py:29: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_numeric['mhw_category'] = df['mhw_category'].replace(replace_category)

((4066, 68), (4066,))

In [21]:
shuffled_df_numeric.dtypes!= 'float64'

ammonium                  False
ammonium std              False
nitrite                   False
nitrite std               False
nitrate                   False
                          ...
sea surface temp          False
total suspended matter    False
silva_func_diversity      False
mhw_count                  True
mhw_category               True
Length: 70, dtype: bool

In [22]:
# Select columns with at least one NaN
nan_columns = shuffled_df_numeric.columns[shuffled_df_numeric.isna().any()]
df_nan = shuffled_df_numeric[nan_columns]
df_nan

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,shannon_physat_mean,sea surface chlorophyll a,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity
2378,0.011647,0.001062,0.006479,0.001361,4.039602,120.0,38.3375,4.280000e-07,0.000004,NaN,...,NaN,0.077641,711.0,NaN,0.000005,2.430824,0.24514,26.686632,0.042097,NaN
2420,0.019421,0.014966,0.036846,0.047819,5.954987,120.0,58.5974,1.602000e-06,0.000003,NaN,...,0.569672,0.122042,719.0,NaN,0.000009,2.694220,0.16747,27.159315,0.066827,NaN
1940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.234896,719.0,NaN,NaN,NaN,NaN,24.200793,0.120501,NaN
1592,0.040871,0.012805,0.175246,0.095507,11.336968,63.0,19.8401,4.470000e-07,0.000004,NaN,...,NaN,0.821085,746.0,1.82307,NaN,1.292856,2.10580,18.466765,0.397447,NaN
2283,0.025083,0.011750,0.054778,0.047893,6.231764,120.0,30.8058,1.026000e-06,0.000002,NaN,...,NaN,0.307092,704.0,NaN,0.000003,3.432006,NaN,26.730190,0.133896,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,0.012845,0.000930,0.029691,0.004530,0.012457,120.0,26.8609,7.793400e-05,0.001244,NaN,...,NaN,0.089576,729.0,NaN,0.000001,NaN,0.25556,23.675053,0.057862,NaN
1294,0.012506,0.006803,0.005806,0.004141,0.003165,5.0,14.8513,9.725200e-05,0.000805,NaN,...,NaN,0.068194,782.0,NaN,0.000018,0.863877,2.00030,24.192727,0.045416,NaN
860,0.012245,0.000652,0.002289,0.000248,0.014058,120.0,16.8437,1.095600e-04,0.001074,NaN,...,0.694640,0.131712,687.0,NaN,0.000025,1.659314,0.28220,29.767761,0.066230,NaN
3507,0.014199,0.009693,0.025725,0.011551,8.367322,0.0,NaN,3.298130e-04,0.000990,NaN,...,NaN,0.239868,1440.0,NaN,NaN,0.295831,NaN,4.301265,NaN,NaN
3174,0.013436,0.005138,0.023813,0.025492,0.096477,120.0,34.6955,1.703370e-04,0.001101,NaN,...,NaN,0.273363,695.0,NaN,0.000005,2.066890,0.44063,17.644545,0.219743,NaN

In [23]:
class_0 = shuffled_df_numeric[shuffled_df_numeric['mhw_category'] == 3]
df_0 = pd.DataFrame(class_0.mean(), index = shuffled_df_numeric.columns)
trans_0 = df_0.transpose()
trans_0

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count,mhw_category
0,0.013131,0.002737,0.114781,0.067715,2.422716,24.0,25.307635,0.000081,0.000895,0.744101,...,615.870968,NaN,0.000129,1.560198,2.662706,14.38792,0.205713,7.166583,1.0,3.0

In [24]:
class_1 = shuffled_df_numeric[shuffled_df_numeric['mhw_category'] == 0]
df_1 = pd.DataFrame(class_1.mean(), index = shuffled_df_numeric.columns)
trans_1 = df_1.transpose()
trans_1

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count,mhw_category
0,0.019229,0.007081,0.06905,0.033821,3.155409,84.41794,31.717957,0.000056,0.00064,0.740644,...,784.585313,2.170018,0.000048,1.564433,0.756132,18.126757,0.175672,7.16479,0.0,0.0

In [25]:
class_2 = shuffled_df_numeric[shuffled_df_numeric['mhw_category'] == 2]
df_2 = pd.DataFrame(class_2.mean(), index = shuffled_df_numeric.columns)
trans_2 = df_2.transpose()
trans_2

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count,mhw_category
0,0.037637,0.031089,0.06056,0.037203,2.068024,84.958084,32.338338,0.000104,0.001038,0.751127,...,802.778378,0.7966,0.000047,1.317775,1.654592,19.231881,0.225873,7.207324,1.27027,2.0

In [26]:
class_3 = shuffled_df_numeric[shuffled_df_numeric['mhw_category'] == 1]
df_3 = pd.DataFrame(class_3.mean(), index = shuffled_df_numeric.columns)
trans_3 = df_3.transpose()
trans_3

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count,mhw_category
0,0.016158,0.003335,0.068334,0.03142,1.346728,91.725777,27.769882,0.00007,0.001078,0.741363,...,767.034884,1.429883,0.000075,1.660023,0.917046,21.952846,0.140689,7.158227,1.190083,1.0

In [27]:
merged_df = trans_0.merge(trans_1, how = 'outer')
merged_df_1 = merged_df.merge(trans_2, how = 'outer')
merged_df_2 = merged_df_1.merge(trans_3, how = 'outer')
merged_df_2

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count,mhw_category
0,0.013131,0.002737,0.114781,0.067715,2.422716,24.000000,25.307635,0.000081,0.000895,0.744101,...,615.870968,NaN,0.000129,1.560198,2.662706,14.387920,0.205713,7.166583,1.000000,3.0
1,0.016158,0.003335,0.068334,0.031420,1.346728,91.725777,27.769882,0.000070,0.001078,0.741363,...,767.034884,1.429883,0.000075,1.660023,0.917046,21.952846,0.140689,7.158227,1.190083,1.0
2,0.019229,0.007081,0.069050,0.033821,3.155409,84.417940,31.717957,0.000056,0.000640,0.740644,...,784.585313,2.170018,0.000048,1.564433,0.756132,18.126757,0.175672,7.164790,0.000000,0.0
3,0.037637,0.031089,0.060560,0.037203,2.068024,84.958084,32.338338,0.000104,0.001038,0.751127,...,802.778378,0.796600,0.000047,1.317775,1.654592,19.231881,0.225873,7.207324,1.270270,2.0

In [28]:
fin_mean = pd.DataFrame(merged_df_2.mean(), index = shuffled_df_numeric.columns)
trans_fin = fin_mean.transpose()
trans_fin

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count,mhw_category
0,0.021539,0.01106,0.078181,0.04254,2.248219,71.27545,29.283453,0.000078,0.000913,0.744309,...,742.567386,1.4655,0.000074,1.525607,1.497619,18.424851,0.186987,7.174231,0.865088,1.5

In [29]:
# Fill NaN values in df_nan using trans_fin's first row where columns match
for column in df_numeric.columns:
    if column in trans_fin.columns:
        fill_value = trans_fin[column].iloc[0]  # Use the first row's value
        df_numeric[column] = df_numeric[column].fillna(fill_value)
df_numeric

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count,mhw_category
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.00000,43.135300,1.366370e-04,0.001293,0.744309,...,776.0,1.4655,0.000003,1.190373,0.391360,18.633288,0.146238,7.174231,0,0
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.00000,43.135300,1.366370e-04,0.001293,0.744309,...,776.0,1.4655,0.000003,1.190373,0.391360,18.633288,0.146238,7.174231,0,0
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.00000,43.651700,1.591000e-06,0.001387,0.744309,...,762.0,1.4655,0.000003,0.750963,1.340400,20.026061,0.077717,7.174231,0,0
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.00000,15.897800,5.200000e-07,0.001387,0.744309,...,750.0,1.4655,0.000005,1.320878,0.427630,21.362549,0.060093,7.174231,0,0
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.00000,15.897800,5.200000e-07,0.001387,0.744309,...,750.0,1.4655,0.000005,1.320878,0.427630,21.362549,0.060093,7.174231,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,0.021539,0.011060,0.078181,0.042540,2.248219,71.27545,29.283453,7.769018e-05,0.000913,0.744309,...,518.0,1.4655,0.000074,1.525607,1.497619,12.249180,0.186987,7.174231,0,0
4062,0.021539,0.011060,0.078181,0.042540,2.248219,71.27545,29.283453,7.769018e-05,0.000913,0.744309,...,505.0,1.4655,0.000074,1.525607,1.497619,12.046478,0.186987,7.174231,0,0
4063,0.021539,0.011060,0.078181,0.042540,2.248219,71.27545,29.283453,7.769018e-05,0.000913,0.744309,...,503.0,1.4655,0.000074,1.525607,1.497619,12.308273,0.186987,7.174231,1,1
4064,0.021539,0.011060,0.078181,0.042540,2.248219,71.27545,29.283453,7.769018e-05,0.000913,0.744309,...,504.0,1.4655,0.000074,1.525607,1.497619,18.424851,0.186987,7.174231,0,0
4065,0.021539,0.011060,0.078181,0.042540,2.248219,71.27545,29.283453,7.769018e-05,0.000913,0.744309,...,509.0,1.4655,0.000074,1.525607,1.497619,13.333583,0.186987,7.174231,0,0

In [30]:
df_numeric.to_csv('Categories imputed.csv', index = False)