In [38]:
import pandas as pd

In [59]:
df = pd.read_csv('no_loc_updated.csv')
df['depth, nominal']

0       0-500
1           9
2       0-200
3           9
4           9
        ...
4061        2
4062        2
4063        2
4064        2
4065        2
Name: depth, nominal, Length: 4066, dtype: object

In [40]:
df['depth bathy']

KeyError: 'depth bathy'

In [60]:
# Select columns with at least one NaN
nan_columns = df.columns[df.isna().any()]
df_nan = df[nan_columns]
df_nan

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,shannon_physat_mean,sea surface chlorophyll a,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,43.1353,1.366370e-04,0.001293,NaN,...,NaN,0.248933,776.0,NaN,0.000003,1.190373,0.39136,18.633288,0.146238,NaN
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,43.1353,1.366370e-04,0.001293,NaN,...,NaN,0.248933,776.0,NaN,0.000003,1.190373,0.39136,18.633288,0.146238,NaN
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.0,43.6517,1.591000e-06,0.001387,NaN,...,NaN,0.134939,762.0,NaN,0.000003,0.750963,1.34040,20.026061,0.077717,NaN
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,15.8978,5.200000e-07,0.001387,NaN,...,NaN,0.095097,750.0,NaN,0.000005,1.320878,0.42763,21.362549,0.060093,NaN
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,15.8978,5.200000e-07,0.001387,NaN,...,0.578344,0.095097,750.0,NaN,0.000005,1.320878,0.42763,21.362549,0.060093,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,518.0,NaN,NaN,NaN,NaN,12.249180,NaN,NaN
4062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,505.0,NaN,NaN,NaN,NaN,12.046478,NaN,NaN
4063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,503.0,NaN,NaN,NaN,NaN,12.308273,NaN,NaN
4064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,504.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,509.0,NaN,NaN,NaN,NaN,13.333583,NaN,NaN

In [61]:
df_nan['mhw_count'] =df['mhw_count']
sorted_df = df_nan.sort_values(by='mhw_count')
sorted_df

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_17704\1156264906.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nan['mhw_count'] =df['mhw_count']

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sea surface chlorophyll a,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,43.1353,0.000137,0.001293,NaN,...,0.248933,776.0,NaN,0.000003,1.190373,0.39136,18.633288,0.146238,NaN,0
2535,0.015840,0.001522,0.005883,0.001725,0.002451,120.0,19.7103,0.000114,0.000199,NaN,...,0.070611,718.0,NaN,0.000012,1.510452,0.38534,26.336557,NaN,NaN,0
2536,0.015840,0.001522,0.005883,0.001725,0.002451,120.0,19.1657,0.000114,0.000199,NaN,...,0.077976,718.0,NaN,0.000006,1.510452,0.18662,26.399653,NaN,NaN,0
2537,0.015840,0.001522,0.005883,0.001725,0.002451,120.0,14.7688,0.000114,0.000199,NaN,...,0.070611,718.0,NaN,0.000010,1.510452,0.23593,26.336557,NaN,NaN,0
2538,0.015840,0.001522,0.005883,0.001725,0.002451,120.0,14.7688,0.000114,0.000199,NaN,...,0.068394,718.0,NaN,0.000010,1.510452,0.23593,26.336557,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,0.011100,0.001074,0.007564,0.001626,0.013671,49.0,15.6699,0.000130,0.001000,NaN,...,0.156935,665.0,NaN,0.000167,1.155264,0.57095,26.699897,0.158360,NaN,3
902,0.011100,0.001074,0.007564,0.001626,0.013671,49.0,15.6699,0.000130,0.001000,NaN,...,0.156935,665.0,NaN,0.000167,1.155264,0.57095,26.699897,0.158360,NaN,3
901,0.011100,0.001074,0.007564,0.001626,0.013671,49.0,15.6699,0.000130,0.001000,NaN,...,0.156935,665.0,NaN,0.000167,1.155264,0.57095,26.699897,0.158360,NaN,3
905,0.011100,0.001074,0.007564,0.001626,0.013671,49.0,15.6699,0.000130,0.001000,NaN,...,0.159699,665.0,NaN,0.000167,1.155264,0.57095,26.699897,0.156559,NaN,3
898,0.011100,0.001074,0.007564,0.001626,0.013671,49.0,15.6699,0.000130,0.001000,NaN,...,0.157995,665.0,NaN,0.000167,1.155264,0.57095,26.709038,0.159464,NaN,3

In [62]:
class_0 = sorted_df[sorted_df['mhw_count'] == 0]
df_0 = pd.DataFrame(class_0.mean(), index = sorted_df.columns)
trans_0 = df_0.transpose()
trans_0

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sea surface chlorophyll a,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count
0,0.019229,0.007081,0.06905,0.033821,3.155409,84.41794,31.717957,0.000056,0.00064,0.740644,...,0.474826,784.585313,2.170018,0.000048,1.564433,0.756132,18.126757,0.175672,7.16479,0.0

In [63]:
class_1 = sorted_df[sorted_df['mhw_count'] == 1]
df_1 = pd.DataFrame(class_1.mean(), index = sorted_df.columns)
trans_1 = df_1.transpose()

In [64]:
class_2 = sorted_df[sorted_df['mhw_count'].isin([2, 3])]
print(class_2)
df_2 = pd.DataFrame(class_2.mean(), index = sorted_df.columns)
trans_2 = df_2.transpose()
trans_2

      ammonium  ammonium std   nitrite  nitrite std   nitrate    age  \
3498  0.020513      0.014564  0.022492     0.012975  7.059148    0.0
3322  0.027012      0.012327  0.039164     0.031951  0.218452  120.0
3323  0.027012      0.012327  0.039164     0.031951  0.218452  120.0
3324  0.027012      0.012327  0.039164     0.031951  0.218452  120.0
3326  0.027012      0.012327  0.039164     0.031951  0.218452  120.0
...        ...           ...       ...          ...       ...    ...
903   0.011100      0.001074  0.007564     0.001626  0.013671   49.0
902   0.011100      0.001074  0.007564     0.001626  0.013671   49.0
901   0.011100      0.001074  0.007564     0.001626  0.013671   49.0
905   0.011100      0.001074  0.007564     0.001626  0.013671   49.0
898   0.011100      0.001074  0.007564     0.001626  0.013671   49.0

      chlorophyll a  iron std      iron  functional evenness  ...  \
3498            NaN  0.000371  0.000951                  NaN  ...
3322        56.7471  0.000195  0.001043                  NaN  ...
3323        56.7471  0.000195  0.001043                  NaN  ...
3324            NaN  0.000195  0.001043                  NaN  ...
3326        40.0462  0.000195  0.001043                  NaN  ...
...             ...       ...       ...                  ...  ...
903         15.6699  0.000130  0.001000                  NaN  ...
902         15.6699  0.000130  0.001000                  NaN  ...
901         15.6699  0.000130  0.001000                  NaN  ...
905         15.6699  0.000130  0.001000                  NaN  ...
898         15.6699  0.000130  0.001000                  NaN  ...

      sea surface chlorophyll a  sunshine duration  sea surface fluorescence  \
3498                   0.206924             1440.0                       NaN
3322                   0.195586              742.0                       NaN
3323                   0.195586              742.0                       NaN
3324                        NaN              742.0                       NaN
3326                        NaN              742.0                       NaN
...                         ...                ...                       ...
903                    0.156935              665.0                       NaN
902                    0.156935              665.0                       NaN
901                    0.156935              665.0                       NaN
905                    0.159699              665.0                       NaN
898                    0.157995              665.0                       NaN

      strain sub-mesoscale  sea surface quantum fluorescence  \
3498                   NaN                          0.304977
3322              0.000009                               NaN
3323              0.000009                               NaN
3324                   NaN                               NaN
3326              0.000058                               NaN
...                    ...                               ...
903               0.000167                          1.155264
902               0.000167                          1.155264
901               0.000167                          1.155264
905               0.000167                          1.155264
898               0.000167                          1.155264

      sea surface temp grad  sea surface temp  total suspended matter  \
3498                    NaN          5.197963                     NaN
3322                1.49650         13.386999                0.203947
3323                1.49650         13.386999                0.203947
3324                    NaN               NaN                     NaN
3326                0.82247         13.386999                0.193412
...                     ...               ...                     ...
903                 0.57095         26.699897                0.158360
902                 0.57095         26.699897                0.158360
901                 0.57095         26.699897                0.158360
905                 0.57095         26.699897                0.156559
898                 0.57095         26.709038                0.159464

      silva_func_diversity  mhw_count
3498                   NaN          2
3322                   NaN          2
3323                   NaN          2
3324                   NaN          2
3326                   NaN          2
...                    ...        ...
903                    NaN          3
902                    NaN          3
901                    NaN          3
905                    NaN          3
898                    NaN          3

[158 rows x 69 columns]

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sea surface chlorophyll a,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count
0,0.01484,0.003873,0.022134,0.010187,0.957297,74.529032,29.831953,0.000095,0.001158,0.740564,...,0.204123,798.810127,NaN,0.00008,1.268478,1.2452,20.729593,0.141108,7.137383,2.044304

In [65]:
merged_df = trans_0.merge(trans_1, how = 'outer')
merged_df_1 = merged_df.merge(trans_2, how = 'outer')
merged_df_1

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sea surface chlorophyll a,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count
0,0.014840,0.003873,0.022134,0.010187,0.957297,74.529032,29.831953,0.000095,0.001158,0.740564,...,0.204123,798.810127,NaN,0.000080,1.268478,1.245200,20.729593,0.141108,7.137383,2.044304
1,0.019229,0.007081,0.069050,0.033821,3.155409,84.417940,31.717957,0.000056,0.000640,0.740644,...,0.474826,784.585313,2.170018,0.000048,1.564433,0.756132,18.126757,0.175672,7.164790,0.000000
2,0.022424,0.011018,0.080712,0.040542,1.709734,90.769492,28.346901,0.000073,0.001036,0.744172,...,0.537648,762.346970,1.384648,0.000069,1.661471,1.120834,21.092802,0.168736,7.173489,1.000000

In [66]:
fin_mean = pd.DataFrame(merged_df_1.mean(), index = sorted_df.columns)
trans_fin = fin_mean.transpose()
trans_fin

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sea surface chlorophyll a,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count
0,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,29.965604,0.000075,0.000945,0.741793,...,0.405532,781.914136,1.777333,0.000066,1.498127,1.040722,19.983051,0.161839,7.158554,1.014768

In [68]:
# Fill NaN values in df_nan using trans_fin's first row where columns match
for column in df_nan.columns:
    if column in trans_fin.columns:
        fill_value = trans_fin[column].iloc[0]  # Use the first row's value
        df_nan[column] = df_nan[column].fillna(fill_value)
df_nan

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_17704\3708048936.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nan[column] = df_nan[column].fillna(fill_value)

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,chlorophyll a,iron std,iron,functional evenness,...,sea surface chlorophyll a,sunshine duration,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,silva_func_diversity,mhw_count
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.000000,43.135300,1.366370e-04,0.001293,0.741793,...,0.248933,776.0,1.777333,0.000003,1.190373,0.391360,18.633288,0.146238,7.158554,0
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.000000,43.135300,1.366370e-04,0.001293,0.741793,...,0.248933,776.0,1.777333,0.000003,1.190373,0.391360,18.633288,0.146238,7.158554,0
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.000000,43.651700,1.591000e-06,0.001387,0.741793,...,0.134939,762.0,1.777333,0.000003,0.750963,1.340400,20.026061,0.077717,7.158554,0
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.000000,15.897800,5.200000e-07,0.001387,0.741793,...,0.095097,750.0,1.777333,0.000005,1.320878,0.427630,21.362549,0.060093,7.158554,0
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.000000,15.897800,5.200000e-07,0.001387,0.741793,...,0.095097,750.0,1.777333,0.000005,1.320878,0.427630,21.362549,0.060093,7.158554,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,29.965604,7.484049e-05,0.000945,0.741793,...,0.405532,518.0,1.777333,0.000066,1.498127,1.040722,12.249180,0.161839,7.158554,0
4062,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,29.965604,7.484049e-05,0.000945,0.741793,...,0.405532,505.0,1.777333,0.000066,1.498127,1.040722,12.046478,0.161839,7.158554,0
4063,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,29.965604,7.484049e-05,0.000945,0.741793,...,0.405532,503.0,1.777333,0.000066,1.498127,1.040722,12.308273,0.161839,7.158554,1
4064,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,29.965604,7.484049e-05,0.000945,0.741793,...,0.405532,504.0,1.777333,0.000066,1.498127,1.040722,19.983051,0.161839,7.158554,0
4065,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,29.965604,7.484049e-05,0.000945,0.741793,...,0.405532,509.0,1.777333,0.000066,1.498127,1.040722,13.333583,0.161839,7.158554,0

In [49]:
done = df_nan.to_csv('impute_mean_classes_no_loc.csv', index = False)