In [45]:
import pandas as pd

In [46]:
df = pd.read_csv('TARA_mhws_3.csv')
df['latitude']

0       44.4013
1       44.4013
2       39.0564
3       36.7320
4       36.7320
         ...
4061    48.7130
4062    49.8982
4063    49.9416
4064    49.6001
4065    48.8262
Name: latitude, Length: 4066, dtype: float64

In [20]:
# Select columns with at least one NaN
nan_columns = df_1.columns[df_1.isna().any()]
df_nan = df_1[nan_columns]
df_nan['latitude']

KeyError: 'latitude'

In [47]:
def numeric_columns(df):
    numeric_cols = []
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            numeric_cols.append(col)
    return numeric_cols
numeric_cols = numeric_columns(df)
# Create a copy of the DataFrame
df_numeric = df[numeric_cols].copy()

# Now you can safely modify df_numeric
#df_numeric['mhw_count'] = df_numeric['mhw_count'].astype(str)

#df_numeric.loc[df_numeric['mhw_count'].isin(['2', '3']), 'mhw_count'] = '2+'
#df_nan['mhw_count'] =df['mhw_count']
sorted_df = df_numeric.sort_values(by='mhw_count')
sorted_df.dtypes

ammonium                  float64
ammonium std              float64
nitrite                   float64
nitrite std               float64
nitrate                   float64
                           ...
total suspended matter    float64
u                         float64
v                         float64
silva_func_diversity      float64
mhw_count                   int64
Length: 81, dtype: object

In [48]:
class_0 = sorted_df[sorted_df['mhw_count'] == 0]
df_0 = pd.DataFrame(class_0.mean(), index = sorted_df.columns)
trans_0 = df_0.transpose()
trans_0

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,chlorophyll a,distance closest,iron std,...,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,u,v,silva_func_diversity,mhw_count
0,0.019229,0.007081,0.06905,0.033821,3.155409,84.41794,-2817.110633,31.717957,328.870899,0.000056,...,2.170018,0.000048,1.564433,0.756132,18.126757,0.175672,1.097232,3.475669,7.16479,0.0

In [49]:
class_1 = sorted_df[sorted_df['mhw_count'] == 1]
df_1 = pd.DataFrame(class_1.mean(), index = sorted_df.columns)
trans_1 = df_1.transpose()
trans_1

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,chlorophyll a,distance closest,iron std,...,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,u,v,silva_func_diversity,mhw_count
0,0.022424,0.011018,0.080712,0.040542,1.709734,90.769492,-2915.838762,28.346901,285.030278,0.000073,...,1.384648,0.000069,1.661471,1.120834,21.092802,0.168736,6.172114,4.248806,7.173489,1.0

In [50]:
class_2 = sorted_df[sorted_df['mhw_count'].isin([2, 3])]
print(class_2)
df_2 = pd.DataFrame(class_2.mean(), index = sorted_df.columns)
trans_2 = df_2.transpose()
trans_2

      ammonium  ammonium std   nitrite  nitrite std   nitrate    age  \
3498  0.020513      0.014564  0.022492     0.012975  7.059148    0.0
3322  0.027012      0.012327  0.039164     0.031951  0.218452  120.0
3323  0.027012      0.012327  0.039164     0.031951  0.218452  120.0
3324  0.027012      0.012327  0.039164     0.031951  0.218452  120.0
3326  0.027012      0.012327  0.039164     0.031951  0.218452  120.0
...        ...           ...       ...          ...       ...    ...
903   0.011100      0.001074  0.007564     0.001626  0.013671   49.0
902   0.011100      0.001074  0.007564     0.001626  0.013671   49.0
901   0.011100      0.001074  0.007564     0.001626  0.013671   49.0
905   0.011100      0.001074  0.007564     0.001626  0.013671   49.0
898   0.011100      0.001074  0.007564     0.001626  0.013671   49.0

      depth bathy  chlorophyll a  distance closest  iron std  ...  \
3498          NaN            NaN               NaN  0.000371  ...
3322      -3669.0        56.7471          596.1715  0.000195  ...
3323      -3669.0        56.7471          596.1715  0.000195  ...
3324          NaN            NaN               NaN  0.000195  ...
3326      -3981.0        40.0462          620.9733  0.000195  ...
...           ...            ...               ...       ...  ...
903       -2115.0        15.6699          182.7374  0.000130  ...
902       -2115.0        15.6699          182.7374  0.000130  ...
901       -2115.0        15.6699          182.7374  0.000130  ...
905       -2115.0        15.6699          182.7374  0.000130  ...
898       -2115.0        15.6699          182.7374  0.000130  ...

      sea surface fluorescence  strain sub-mesoscale  \
3498                       NaN                   NaN
3322                       NaN              0.000009
3323                       NaN              0.000009
3324                       NaN                   NaN
3326                       NaN              0.000058
...                        ...                   ...
903                        NaN              0.000167
902                        NaN              0.000167
901                        NaN              0.000167
905                        NaN              0.000167
898                        NaN              0.000167

      sea surface quantum fluorescence  sea surface temp grad  \
3498                          0.304977                    NaN
3322                               NaN                1.49650
3323                               NaN                1.49650
3324                               NaN                    NaN
3326                               NaN                0.82247
...                                ...                    ...
903                           1.155264                0.57095
902                           1.155264                0.57095
901                           1.155264                0.57095
905                           1.155264                0.57095
898                           1.155264                0.57095

      sea surface temp  total suspended matter          u         v  \
3498          5.197963                     NaN  -1.657741  0.853310
3322         13.386999                0.203947  -1.072960 -3.254783
3323         13.386999                0.203947  -1.072960 -3.254783
3324               NaN                     NaN  -1.072960 -3.254783
3326         13.386999                0.193412  -1.072960 -3.254783
...                ...                     ...        ...       ...
903          26.699897                0.158360  38.139888  7.132594
902          26.699897                0.158360  38.139888  7.132594
901          26.699897                0.158360  38.139888  7.132594
905          26.699897                0.156559  38.139888  7.132594
898          26.709038                0.159464  38.139888  7.132594

      silva_func_diversity  mhw_count
3498                   NaN          2
3322                   NaN          2
3323                   NaN          2
3324                   NaN          2
3326                   NaN          2
...                    ...        ...
903                    NaN          3
902                    NaN          3
901                    NaN          3
905                    NaN          3
898                    NaN          3

[158 rows x 81 columns]

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,chlorophyll a,distance closest,iron std,...,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,u,v,silva_func_diversity,mhw_count
0,0.01484,0.003873,0.022134,0.010187,0.957297,74.529032,-2483.296053,29.831953,227.057727,0.000095,...,NaN,0.00008,1.268478,1.2452,20.729593,0.141108,13.560843,0.799303,7.137383,2.044304

In [51]:
merged_df = trans_0.merge(trans_1, how = 'outer')
merged_df_1 = merged_df.merge(trans_2, how = 'outer')
merged_df_1

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,chlorophyll a,distance closest,iron std,...,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,u,v,silva_func_diversity,mhw_count
0,0.014840,0.003873,0.022134,0.010187,0.957297,74.529032,-2483.296053,29.831953,227.057727,0.000095,...,NaN,0.000080,1.268478,1.245200,20.729593,0.141108,13.560843,0.799303,7.137383,2.044304
1,0.019229,0.007081,0.069050,0.033821,3.155409,84.417940,-2817.110633,31.717957,328.870899,0.000056,...,2.170018,0.000048,1.564433,0.756132,18.126757,0.175672,1.097232,3.475669,7.164790,0.000000
2,0.022424,0.011018,0.080712,0.040542,1.709734,90.769492,-2915.838762,28.346901,285.030278,0.000073,...,1.384648,0.000069,1.661471,1.120834,21.092802,0.168736,6.172114,4.248806,7.173489,1.000000

In [52]:
fin_mean = pd.DataFrame(merged_df_1.mean(), index = sorted_df.columns)
trans_fin = fin_mean.transpose()
trans_fin

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,chlorophyll a,distance closest,iron std,...,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,u,v,silva_func_diversity,mhw_count
0,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,-2738.748483,29.965604,280.319635,0.000075,...,1.777333,0.000066,1.498127,1.040722,19.983051,0.161839,6.943396,2.841259,7.158554,1.014768

In [53]:
df_numeric['ammonium'] = df_numeric['ammonium'].fillna(trans_fin.loc[0,'ammonium'])
df_numeric

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,chlorophyll a,distance closest,iron std,...,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,u,v,silva_func_diversity,mhw_count
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,-4948.0,43.1353,143.7212,1.366370e-04,...,NaN,0.000003,1.190373,0.39136,18.633288,0.146238,-3.855836,-8.864694,NaN,0
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.0,-4948.0,43.1353,143.7212,1.366370e-04,...,NaN,0.000003,1.190373,0.39136,18.633288,0.146238,-3.855836,-8.864694,NaN,0
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.0,-3559.0,43.6517,118.4945,1.591000e-06,...,NaN,0.000003,0.750963,1.34040,20.026061,0.077717,-0.631608,-0.773749,NaN,0
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,-3316.0,15.8978,136.9644,5.200000e-07,...,NaN,0.000005,1.320878,0.42763,21.362549,0.060093,-3.196994,6.553035,NaN,0
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.0,-3316.0,15.8978,136.9644,5.200000e-07,...,NaN,0.000005,1.320878,0.42763,21.362549,0.060093,-3.196994,6.553035,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,0.018831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12.249180,NaN,NaN,NaN,NaN,0
4062,0.018831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12.046478,NaN,NaN,NaN,NaN,0
4063,0.018831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12.308273,NaN,NaN,NaN,NaN,1
4064,0.018831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4065,0.018831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.333583,NaN,NaN,NaN,NaN,0

In [54]:
# Fill NaN values in df_nan using trans_fin's first row where columns match
for column in df_numeric.columns:
    if column in trans_fin.columns:
        fill_value = trans_fin[column].iloc[0]  # Use the first row's value
        df_numeric[column] = df_numeric[column].fillna(fill_value)
df_numeric

,ammonium,ammonium std,nitrite,nitrite std,nitrate,age,depth bathy,chlorophyll a,distance closest,iron std,...,sea surface fluorescence,strain sub-mesoscale,sea surface quantum fluorescence,sea surface temp grad,sea surface temp,total suspended matter,u,v,silva_func_diversity,mhw_count
0,0.017782,0.003814,0.033199,0.021603,0.006594,120.000000,-4948.000000,43.135300,143.721200,1.366370e-04,...,1.777333,0.000003,1.190373,0.391360,18.633288,0.146238,-3.855836,-8.864694,7.158554,0
1,0.017782,0.003814,0.033199,0.021603,0.006594,120.000000,-4948.000000,43.135300,143.721200,1.366370e-04,...,1.777333,0.000003,1.190373,0.391360,18.633288,0.146238,-3.855836,-8.864694,7.158554,0
2,0.019857,0.004334,0.022540,0.003445,0.004371,120.000000,-3559.000000,43.651700,118.494500,1.591000e-06,...,1.777333,0.000003,0.750963,1.340400,20.026061,0.077717,-0.631608,-0.773749,7.158554,0
3,0.019621,0.001549,0.049836,0.016420,0.008997,120.000000,-3316.000000,15.897800,136.964400,5.200000e-07,...,1.777333,0.000005,1.320878,0.427630,21.362549,0.060093,-3.196994,6.553035,7.158554,0
4,0.019621,0.001549,0.049836,0.016420,0.008997,120.000000,-3316.000000,15.897800,136.964400,5.200000e-07,...,1.777333,0.000005,1.320878,0.427630,21.362549,0.060093,-3.196994,6.553035,7.158554,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,-2738.748483,29.965604,280.319635,7.484049e-05,...,1.777333,0.000066,1.498127,1.040722,12.249180,0.161839,6.943396,2.841259,7.158554,0
4062,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,-2738.748483,29.965604,280.319635,7.484049e-05,...,1.777333,0.000066,1.498127,1.040722,12.046478,0.161839,6.943396,2.841259,7.158554,0
4063,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,-2738.748483,29.965604,280.319635,7.484049e-05,...,1.777333,0.000066,1.498127,1.040722,12.308273,0.161839,6.943396,2.841259,7.158554,1
4064,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,-2738.748483,29.965604,280.319635,7.484049e-05,...,1.777333,0.000066,1.498127,1.040722,19.983051,0.161839,6.943396,2.841259,7.158554,0
4065,0.018831,0.007324,0.057298,0.028184,1.940813,83.238821,-2738.748483,29.965604,280.319635,7.484049e-05,...,1.777333,0.000066,1.498127,1.040722,13.333583,0.161839,6.943396,2.841259,7.158554,0

In [56]:
df_numeric[['date/time', 'depth, nominal']] = df[['date/time', 'depth, nominal']]
df_numeric[['date/time', 'depth, nominal']]

             date/time depth, nominal
0     2009-09-07T15:30          0-500
1     2009-09-07T16:10              9
2     2009-09-09T18:30          0-200
3     2009-09-13T11:30              9
4     2009-09-13T12:00              9
...                ...            ...
4061  2013-11-29T11:13              2
4062  2013-12-01T15:38              2
4063  2013-12-02T14:16              2
4064  2013-12-03T15:23              2
4065  2013-12-04T14:48              2

[4066 rows x 2 columns]

In [94]:
done = df_nan.to_csv('impute_mean_classes_no_loc.csv', index = False)

In [57]:
new = df_numeric.to_csv('impute_mean_classes_new.csv', index = False)